// Code generated by entc, DO NOT EDIT.

package mstcustomer

const (
	// Label holds the string label denoting the mstcustomer type in the database.
	Label = "mst_customer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCustDet holds the string denoting the custdet field in the database.
	FieldCustDet = "cust_det"
	// FieldCustCode holds the string denoting the custcode field in the database.
	FieldCustCode = "cust_code"
	// FieldCustAddr holds the string denoting the custaddr field in the database.
	FieldCustAddr = "cust_addr"
	// FieldCustPlace holds the string denoting the custplace field in the database.
	FieldCustPlace = "cust_place"
	// FieldCustContact holds the string denoting the custcontact field in the database.
	FieldCustContact = "cust_contact"
	// FieldCustTel holds the string denoting the custtel field in the database.
	FieldCustTel = "cust_tel"
	// FieldCustEmail holds the string denoting the custemail field in the database.
	FieldCustEmail = "cust_email"
	// FieldCustUrl holds the string denoting the custurl field in the database.
	FieldCustUrl = "cust_url"
	// FieldCustBanner1 holds the string denoting the custbanner1 field in the database.
	FieldCustBanner1 = "cust_banner1"
	// FieldCustBanner2 holds the string denoting the custbanner2 field in the database.
	FieldCustBanner2 = "cust_banner2"
	// FieldCustLogoUrl holds the string denoting the custlogourl field in the database.
	FieldCustLogoUrl = "cust_logo_url"
	// Table holds the table name of the mstcustomer in the database.
	Table = "mst_customers"
)

// Columns holds all SQL columns for mstcustomer fields.
var Columns = []string{
	FieldID,
	FieldCustDet,
	FieldCustCode,
	FieldCustAddr,
	FieldCustPlace,
	FieldCustContact,
	FieldCustTel,
	FieldCustEmail,
	FieldCustUrl,
	FieldCustBanner1,
	FieldCustBanner2,
	FieldCustLogoUrl,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CustDetValidator is a validator for the "CustDet" field. It is called by the builders before save.
	CustDetValidator func(string) error
	// CustCodeValidator is a validator for the "CustCode" field. It is called by the builders before save.
	CustCodeValidator func(string) error
	// CustAddrValidator is a validator for the "CustAddr" field. It is called by the builders before save.
	CustAddrValidator func(string) error
	// CustPlaceValidator is a validator for the "CustPlace" field. It is called by the builders before save.
	CustPlaceValidator func(string) error
	// CustContactValidator is a validator for the "CustContact" field. It is called by the builders before save.
	CustContactValidator func(string) error
	// CustTelValidator is a validator for the "CustTel" field. It is called by the builders before save.
	CustTelValidator func(string) error
	// CustEmailValidator is a validator for the "CustEmail" field. It is called by the builders before save.
	CustEmailValidator func(string) error
	// CustUrlValidator is a validator for the "CustUrl" field. It is called by the builders before save.
	CustUrlValidator func(string) error
	// CustBanner1Validator is a validator for the "CustBanner1" field. It is called by the builders before save.
	CustBanner1Validator func(string) error
	// CustBanner2Validator is a validator for the "CustBanner2" field. It is called by the builders before save.
	CustBanner2Validator func(string) error
	// CustLogoUrlValidator is a validator for the "CustLogoUrl" field. It is called by the builders before save.
	CustLogoUrlValidator func(string) error
)
