// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MstCustomersColumns holds the columns for the "mst_customers" table.
	MstCustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "cust_det", Type: field.TypeString},
		{Name: "cust_code", Type: field.TypeString},
		{Name: "cust_addr", Type: field.TypeString},
		{Name: "cust_place", Type: field.TypeString},
		{Name: "cust_contact", Type: field.TypeString},
		{Name: "cust_tel", Type: field.TypeString},
		{Name: "cust_email", Type: field.TypeString},
		{Name: "cust_url", Type: field.TypeString},
		{Name: "cust_banner1", Type: field.TypeString},
		{Name: "cust_banner2", Type: field.TypeString},
		{Name: "cust_logo_url", Type: field.TypeString},
	}
	// MstCustomersTable holds the schema information for the "mst_customers" table.
	MstCustomersTable = &schema.Table{
		Name:       "mst_customers",
		Columns:    MstCustomersColumns,
		PrimaryKey: []*schema.Column{MstCustomersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MstCustomersTable,
	}
)

func init() {
}
