// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (mc *MstCustomerQuery) CollectFields(ctx context.Context, satisfies ...string) *MstCustomerQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		mc = mc.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return mc
}

func (mc *MstCustomerQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *MstCustomerQuery {
	return mc
}
