// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ent

type MstCustomerInput struct {
	CustDet     string `json:"CustDet"`
	CustCode    string `json:"CustCode"`
	CustAddr    string `json:"CustAddr"`
	CustPlace   string `json:"CustPlace"`
	CustContact string `json:"CustContact"`
	CustTel     string `json:"CustTel"`
	CustEmail   string `json:"CustEmail"`
	CustURL     string `json:"CustUrl"`
	CustBanner1 string `json:"CustBanner1"`
	CustBanner2 string `json:"CustBanner2"`
	CustLogoURL string `json:"CustLogoUrl"`
}
