// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"myeduate/ent/mstcustomer"
	"myeduate/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MstCustomerQuery is the builder for querying MstCustomer entities.
type MstCustomerQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MstCustomer
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MstCustomerQuery builder.
func (mcq *MstCustomerQuery) Where(ps ...predicate.MstCustomer) *MstCustomerQuery {
	mcq.predicates = append(mcq.predicates, ps...)
	return mcq
}

// Limit adds a limit step to the query.
func (mcq *MstCustomerQuery) Limit(limit int) *MstCustomerQuery {
	mcq.limit = &limit
	return mcq
}

// Offset adds an offset step to the query.
func (mcq *MstCustomerQuery) Offset(offset int) *MstCustomerQuery {
	mcq.offset = &offset
	return mcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mcq *MstCustomerQuery) Unique(unique bool) *MstCustomerQuery {
	mcq.unique = &unique
	return mcq
}

// Order adds an order step to the query.
func (mcq *MstCustomerQuery) Order(o ...OrderFunc) *MstCustomerQuery {
	mcq.order = append(mcq.order, o...)
	return mcq
}

// First returns the first MstCustomer entity from the query.
// Returns a *NotFoundError when no MstCustomer was found.
func (mcq *MstCustomerQuery) First(ctx context.Context) (*MstCustomer, error) {
	nodes, err := mcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mstcustomer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mcq *MstCustomerQuery) FirstX(ctx context.Context) *MstCustomer {
	node, err := mcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MstCustomer ID from the query.
// Returns a *NotFoundError when no MstCustomer ID was found.
func (mcq *MstCustomerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mstcustomer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mcq *MstCustomerQuery) FirstIDX(ctx context.Context) int {
	id, err := mcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MstCustomer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one MstCustomer entity is not found.
// Returns a *NotFoundError when no MstCustomer entities are found.
func (mcq *MstCustomerQuery) Only(ctx context.Context) (*MstCustomer, error) {
	nodes, err := mcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mstcustomer.Label}
	default:
		return nil, &NotSingularError{mstcustomer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mcq *MstCustomerQuery) OnlyX(ctx context.Context) *MstCustomer {
	node, err := mcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MstCustomer ID in the query.
// Returns a *NotSingularError when exactly one MstCustomer ID is not found.
// Returns a *NotFoundError when no entities are found.
func (mcq *MstCustomerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mstcustomer.Label}
	default:
		err = &NotSingularError{mstcustomer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mcq *MstCustomerQuery) OnlyIDX(ctx context.Context) int {
	id, err := mcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MstCustomers.
func (mcq *MstCustomerQuery) All(ctx context.Context) ([]*MstCustomer, error) {
	if err := mcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mcq *MstCustomerQuery) AllX(ctx context.Context) []*MstCustomer {
	nodes, err := mcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MstCustomer IDs.
func (mcq *MstCustomerQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := mcq.Select(mstcustomer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mcq *MstCustomerQuery) IDsX(ctx context.Context) []int {
	ids, err := mcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mcq *MstCustomerQuery) Count(ctx context.Context) (int, error) {
	if err := mcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mcq *MstCustomerQuery) CountX(ctx context.Context) int {
	count, err := mcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mcq *MstCustomerQuery) Exist(ctx context.Context) (bool, error) {
	if err := mcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mcq *MstCustomerQuery) ExistX(ctx context.Context) bool {
	exist, err := mcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MstCustomerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mcq *MstCustomerQuery) Clone() *MstCustomerQuery {
	if mcq == nil {
		return nil
	}
	return &MstCustomerQuery{
		config:     mcq.config,
		limit:      mcq.limit,
		offset:     mcq.offset,
		order:      append([]OrderFunc{}, mcq.order...),
		predicates: append([]predicate.MstCustomer{}, mcq.predicates...),
		// clone intermediate query.
		sql:  mcq.sql.Clone(),
		path: mcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CustDet string `json:"CustDet,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MstCustomer.Query().
//		GroupBy(mstcustomer.FieldCustDet).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (mcq *MstCustomerQuery) GroupBy(field string, fields ...string) *MstCustomerGroupBy {
	group := &MstCustomerGroupBy{config: mcq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mcq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CustDet string `json:"CustDet,omitempty"`
//	}
//
//	client.MstCustomer.Query().
//		Select(mstcustomer.FieldCustDet).
//		Scan(ctx, &v)
//
func (mcq *MstCustomerQuery) Select(fields ...string) *MstCustomerSelect {
	mcq.fields = append(mcq.fields, fields...)
	return &MstCustomerSelect{MstCustomerQuery: mcq}
}

func (mcq *MstCustomerQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mcq.fields {
		if !mstcustomer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mcq.path != nil {
		prev, err := mcq.path(ctx)
		if err != nil {
			return err
		}
		mcq.sql = prev
	}
	return nil
}

func (mcq *MstCustomerQuery) sqlAll(ctx context.Context) ([]*MstCustomer, error) {
	var (
		nodes = []*MstCustomer{}
		_spec = mcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &MstCustomer{config: mcq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, mcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mcq *MstCustomerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mcq.querySpec()
	return sqlgraph.CountNodes(ctx, mcq.driver, _spec)
}

func (mcq *MstCustomerQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := mcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (mcq *MstCustomerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mstcustomer.Table,
			Columns: mstcustomer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mstcustomer.FieldID,
			},
		},
		From:   mcq.sql,
		Unique: true,
	}
	if unique := mcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mstcustomer.FieldID)
		for i := range fields {
			if fields[i] != mstcustomer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mcq *MstCustomerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mcq.driver.Dialect())
	t1 := builder.Table(mstcustomer.Table)
	columns := mcq.fields
	if len(columns) == 0 {
		columns = mstcustomer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mcq.sql != nil {
		selector = mcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range mcq.predicates {
		p(selector)
	}
	for _, p := range mcq.order {
		p(selector)
	}
	if offset := mcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MstCustomerGroupBy is the group-by builder for MstCustomer entities.
type MstCustomerGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mcgb *MstCustomerGroupBy) Aggregate(fns ...AggregateFunc) *MstCustomerGroupBy {
	mcgb.fns = append(mcgb.fns, fns...)
	return mcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mcgb *MstCustomerGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mcgb.path(ctx)
	if err != nil {
		return err
	}
	mcgb.sql = query
	return mcgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mcgb *MstCustomerGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := mcgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MstCustomerGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(mcgb.fields) > 1 {
		return nil, errors.New("ent: MstCustomerGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := mcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mcgb *MstCustomerGroupBy) StringsX(ctx context.Context) []string {
	v, err := mcgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MstCustomerGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mcgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mstcustomer.Label}
	default:
		err = fmt.Errorf("ent: MstCustomerGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mcgb *MstCustomerGroupBy) StringX(ctx context.Context) string {
	v, err := mcgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MstCustomerGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(mcgb.fields) > 1 {
		return nil, errors.New("ent: MstCustomerGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := mcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mcgb *MstCustomerGroupBy) IntsX(ctx context.Context) []int {
	v, err := mcgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MstCustomerGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mcgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mstcustomer.Label}
	default:
		err = fmt.Errorf("ent: MstCustomerGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mcgb *MstCustomerGroupBy) IntX(ctx context.Context) int {
	v, err := mcgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MstCustomerGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(mcgb.fields) > 1 {
		return nil, errors.New("ent: MstCustomerGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := mcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mcgb *MstCustomerGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := mcgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MstCustomerGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mcgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mstcustomer.Label}
	default:
		err = fmt.Errorf("ent: MstCustomerGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mcgb *MstCustomerGroupBy) Float64X(ctx context.Context) float64 {
	v, err := mcgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MstCustomerGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(mcgb.fields) > 1 {
		return nil, errors.New("ent: MstCustomerGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := mcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mcgb *MstCustomerGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := mcgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MstCustomerGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mcgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mstcustomer.Label}
	default:
		err = fmt.Errorf("ent: MstCustomerGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mcgb *MstCustomerGroupBy) BoolX(ctx context.Context) bool {
	v, err := mcgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mcgb *MstCustomerGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mcgb.fields {
		if !mstcustomer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mcgb *MstCustomerGroupBy) sqlQuery() *sql.Selector {
	selector := mcgb.sql.Select()
	aggregation := make([]string, 0, len(mcgb.fns))
	for _, fn := range mcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mcgb.fields)+len(mcgb.fns))
		for _, f := range mcgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mcgb.fields...)...)
}

// MstCustomerSelect is the builder for selecting fields of MstCustomer entities.
type MstCustomerSelect struct {
	*MstCustomerQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mcs *MstCustomerSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mcs.prepareQuery(ctx); err != nil {
		return err
	}
	mcs.sql = mcs.MstCustomerQuery.sqlQuery(ctx)
	return mcs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mcs *MstCustomerSelect) ScanX(ctx context.Context, v interface{}) {
	if err := mcs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (mcs *MstCustomerSelect) Strings(ctx context.Context) ([]string, error) {
	if len(mcs.fields) > 1 {
		return nil, errors.New("ent: MstCustomerSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := mcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mcs *MstCustomerSelect) StringsX(ctx context.Context) []string {
	v, err := mcs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (mcs *MstCustomerSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mcs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mstcustomer.Label}
	default:
		err = fmt.Errorf("ent: MstCustomerSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mcs *MstCustomerSelect) StringX(ctx context.Context) string {
	v, err := mcs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (mcs *MstCustomerSelect) Ints(ctx context.Context) ([]int, error) {
	if len(mcs.fields) > 1 {
		return nil, errors.New("ent: MstCustomerSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := mcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mcs *MstCustomerSelect) IntsX(ctx context.Context) []int {
	v, err := mcs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (mcs *MstCustomerSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mcs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mstcustomer.Label}
	default:
		err = fmt.Errorf("ent: MstCustomerSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mcs *MstCustomerSelect) IntX(ctx context.Context) int {
	v, err := mcs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (mcs *MstCustomerSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(mcs.fields) > 1 {
		return nil, errors.New("ent: MstCustomerSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := mcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mcs *MstCustomerSelect) Float64sX(ctx context.Context) []float64 {
	v, err := mcs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (mcs *MstCustomerSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mcs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mstcustomer.Label}
	default:
		err = fmt.Errorf("ent: MstCustomerSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mcs *MstCustomerSelect) Float64X(ctx context.Context) float64 {
	v, err := mcs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (mcs *MstCustomerSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(mcs.fields) > 1 {
		return nil, errors.New("ent: MstCustomerSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := mcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mcs *MstCustomerSelect) BoolsX(ctx context.Context) []bool {
	v, err := mcs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (mcs *MstCustomerSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mcs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mstcustomer.Label}
	default:
		err = fmt.Errorf("ent: MstCustomerSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mcs *MstCustomerSelect) BoolX(ctx context.Context) bool {
	v, err := mcs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mcs *MstCustomerSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mcs.sql.Query()
	if err := mcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
