// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"myeduate/ent/mstcustomer"
	"myeduate/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MstCustomerDelete is the builder for deleting a MstCustomer entity.
type MstCustomerDelete struct {
	config
	hooks    []Hook
	mutation *MstCustomerMutation
}

// Where appends a list predicates to the MstCustomerDelete builder.
func (mcd *MstCustomerDelete) Where(ps ...predicate.MstCustomer) *MstCustomerDelete {
	mcd.mutation.Where(ps...)
	return mcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mcd *MstCustomerDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mcd.hooks) == 0 {
		affected, err = mcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MstCustomerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mcd.mutation = mutation
			affected, err = mcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mcd.hooks) - 1; i >= 0; i-- {
			if mcd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcd *MstCustomerDelete) ExecX(ctx context.Context) int {
	n, err := mcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mcd *MstCustomerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: mstcustomer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mstcustomer.FieldID,
			},
		},
	}
	if ps := mcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mcd.driver, _spec)
}

// MstCustomerDeleteOne is the builder for deleting a single MstCustomer entity.
type MstCustomerDeleteOne struct {
	mcd *MstCustomerDelete
}

// Exec executes the deletion query.
func (mcdo *MstCustomerDeleteOne) Exec(ctx context.Context) error {
	n, err := mcdo.mcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mstcustomer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mcdo *MstCustomerDeleteOne) ExecX(ctx context.Context) {
	mcdo.mcd.ExecX(ctx)
}
