// Code generated by entc, DO NOT EDIT.

package ent

import (
	"myeduate/ent/mstcustomer"
	"myeduate/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mstcustomerFields := schema.MstCustomer{}.Fields()
	_ = mstcustomerFields
	// mstcustomerDescCustDet is the schema descriptor for CustDet field.
	mstcustomerDescCustDet := mstcustomerFields[0].Descriptor()
	// mstcustomer.CustDetValidator is a validator for the "CustDet" field. It is called by the builders before save.
	mstcustomer.CustDetValidator = mstcustomerDescCustDet.Validators[0].(func(string) error)
	// mstcustomerDescCustCode is the schema descriptor for CustCode field.
	mstcustomerDescCustCode := mstcustomerFields[1].Descriptor()
	// mstcustomer.CustCodeValidator is a validator for the "CustCode" field. It is called by the builders before save.
	mstcustomer.CustCodeValidator = mstcustomerDescCustCode.Validators[0].(func(string) error)
	// mstcustomerDescCustAddr is the schema descriptor for CustAddr field.
	mstcustomerDescCustAddr := mstcustomerFields[2].Descriptor()
	// mstcustomer.CustAddrValidator is a validator for the "CustAddr" field. It is called by the builders before save.
	mstcustomer.CustAddrValidator = mstcustomerDescCustAddr.Validators[0].(func(string) error)
	// mstcustomerDescCustPlace is the schema descriptor for CustPlace field.
	mstcustomerDescCustPlace := mstcustomerFields[3].Descriptor()
	// mstcustomer.CustPlaceValidator is a validator for the "CustPlace" field. It is called by the builders before save.
	mstcustomer.CustPlaceValidator = mstcustomerDescCustPlace.Validators[0].(func(string) error)
	// mstcustomerDescCustContact is the schema descriptor for CustContact field.
	mstcustomerDescCustContact := mstcustomerFields[4].Descriptor()
	// mstcustomer.CustContactValidator is a validator for the "CustContact" field. It is called by the builders before save.
	mstcustomer.CustContactValidator = mstcustomerDescCustContact.Validators[0].(func(string) error)
	// mstcustomerDescCustTel is the schema descriptor for CustTel field.
	mstcustomerDescCustTel := mstcustomerFields[5].Descriptor()
	// mstcustomer.CustTelValidator is a validator for the "CustTel" field. It is called by the builders before save.
	mstcustomer.CustTelValidator = mstcustomerDescCustTel.Validators[0].(func(string) error)
	// mstcustomerDescCustEmail is the schema descriptor for CustEmail field.
	mstcustomerDescCustEmail := mstcustomerFields[6].Descriptor()
	// mstcustomer.CustEmailValidator is a validator for the "CustEmail" field. It is called by the builders before save.
	mstcustomer.CustEmailValidator = mstcustomerDescCustEmail.Validators[0].(func(string) error)
	// mstcustomerDescCustUrl is the schema descriptor for CustUrl field.
	mstcustomerDescCustUrl := mstcustomerFields[7].Descriptor()
	// mstcustomer.CustUrlValidator is a validator for the "CustUrl" field. It is called by the builders before save.
	mstcustomer.CustUrlValidator = mstcustomerDescCustUrl.Validators[0].(func(string) error)
	// mstcustomerDescCustBanner1 is the schema descriptor for CustBanner1 field.
	mstcustomerDescCustBanner1 := mstcustomerFields[8].Descriptor()
	// mstcustomer.CustBanner1Validator is a validator for the "CustBanner1" field. It is called by the builders before save.
	mstcustomer.CustBanner1Validator = mstcustomerDescCustBanner1.Validators[0].(func(string) error)
	// mstcustomerDescCustBanner2 is the schema descriptor for CustBanner2 field.
	mstcustomerDescCustBanner2 := mstcustomerFields[9].Descriptor()
	// mstcustomer.CustBanner2Validator is a validator for the "CustBanner2" field. It is called by the builders before save.
	mstcustomer.CustBanner2Validator = mstcustomerDescCustBanner2.Validators[0].(func(string) error)
	// mstcustomerDescCustLogoUrl is the schema descriptor for CustLogoUrl field.
	mstcustomerDescCustLogoUrl := mstcustomerFields[10].Descriptor()
	// mstcustomer.CustLogoUrlValidator is a validator for the "CustLogoUrl" field. It is called by the builders before save.
	mstcustomer.CustLogoUrlValidator = mstcustomerDescCustLogoUrl.Validators[0].(func(string) error)
}
