// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MstCustomer is the predicate function for mstcustomer builders.
type MstCustomer func(*sql.Selector)
